name: ui
description: A Helm chart for UI
version: 0.1.5
home: https://k8s.community/
sources:
  - https://github.com/k8s-community/ui
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl
